####################################################################
## Main Configuration YAML, that serves as index for other config
####################################################################

mainConfig:
    deviceConfig: device.yaml
    snmpConfig: snmp.yaml
    netconfConfig: netconf.yaml
    ipfixConfig: ipfix.yaml
    storeConfig: storage.yaml
    parallelTask : 2
    parallelTaskTimeout : 5