{
 "title": "DeviceAnalytics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "deviceId", "query": { "query": "label_values(instance)" } },
   { "name": "interfaceName", "label": "ifName", "query": { "query": "label_values(ifName)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device UpTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysUpTime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Device System Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sys{instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interface Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "InOctets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifInOctets{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutOctets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifOutOctets{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InUcastPkts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifInUcastPkts{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutUcastPkts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifOutUcastPkts{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InDiscards",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifInDiscards{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutDiscards",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifOutDiscards{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifInErrors{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ifOutErrors{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InUnknownProtos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifInUnknownProtos{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InNUcastPkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifInNUcastPkts{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OutNUcastPkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifOutNUcastPkts{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OperStatus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ifOperStatus{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LastChange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "ifLastChange{ifName=\"$interfaceName\", job=\"deviceAnalytics\", instance=\"$deviceId\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}